name: tws
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  splashscreen: ^1.3.5
  country_picker: ^2.0.11
  pin_code_fields: ^7.3.0
  keyboard_actions: ^3.4.0
  carousel_slider: ^3.0.0
  searchable_dropdown: ^1.1.3
  dropdown_search: ^0.4.8
  popup_menu: ^1.0.5
  provider: ^5.0.0
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.7
  file_picker: ^3.0.2+2
  flick_video_player: ^0.3.1
  video_player: ^2.1.9
  visibility_detector: ^0.2.2
  youtube_player_flutter: ^8.0.0
  url_launcher: ^5.2.1
  webview_flutter: ^2.0.0
  simple_animations: ^2.5.0
  date_format: ^2.0.4
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/